name: Attach wait for healthy
description: Attaches the current PR to an asana task, if a task can be identified

inputs:
  github-token:
    description: A github token for the action
    required: true
  check-for-line:
    description: The line to check for
    required: false
    default: The badge was added automatically

runs:
  using: "composite"
  steps:
    - name: Remove status
      env:
        PR_ADDITION_LAST_LINE: ${{ inputs.check-for-line }}
      if: contains(github.event.pull_request.body, '${{ env.PR_ADDITION_LAST_LINE }}')
      uses: actions/github-script@v5
      with:
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          let found = false;
          const prBody = pr.data.body;
          let newBody = prBody.split('\n').filter(line => {
             let tmp = found;
             console.log(line);
             found = line.contains(process.env.PR_ADDITION_LAST_LINE);
             return tmp;
          }).join('\n');
          
          github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.number,
            body: newBody
          });
        github-token: ${{ inputs.github-token }}
