name: Check Code Compliance
description: Checks the code and dependencies for compliant licenses

inputs:
  asana-secret:
    description: The secret to use for the Asana API
    required: true

runs:
  using: "composite"

  steps:
    - name: Create pull request attachments
      uses: Asana/create-app-attachment-github-action@latest
      id: postAttachment
      with:
        asana-secret: ${{ inputs.asana-secret }}
    - name: Log output status
      shell: bash
      run: echo "Status is ${{ steps.postAttachment.outputs.status }}"