name: Attach asana task
description: Attaches the current PR to an asana task, if a task can be identified

inputs:
  asana-secret:
    description: The secret to use for the Asana API
    default: ""
    required: false

runs:
  using: "composite"

  steps:
    - name: Create pull request attachments
      if: inputs.asana-secret != '' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_review')
      uses: Asana/create-app-attachment-github-action@latest
      id: postAttachment
      with:
        asana-secret: ${{ inputs.asana-secret }}
    - name: Log output status
      if: inputs.asana-secret != ''
      shell: bash
      run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
