name: "build-docker-image"
description: "Builds and releases a Docker container"

inputs:
  checkout-ref:
    description: Ref to checkout from Git
    default: ${{ github.event.pull_request.head.sha }}
    required: false
  container-verify-cmd:
    description: "Log entry which shows up if the container starts up successfully after build"
    required: true
  image-registry:
    description: url to the container registry where to push container images too
    required: false
    default: registry.neohelden.com
  maximize-build-space:
    description: Set this to 'true' in case you need to maxmize the disk-space by removing unnecessary software.
    required: false
    default: "false"
  image-registry-username:
    description: Username used to login at the image registry
    required: true
  image-registry-token:
    description: Token use to login at the image registry
    required: true
  registry-org:
    description: Organization within the image registry where to push container images too
    required: false
    default: neohelden
  image-name:
    description: Name of the container image. Default is derived from the repo name.
    required: false
    default: ${{ github.event.repository.name }}
  image-tag:
    description: Tag of the container image
    required: false
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  docker-file:
    description: Full path to the Dockerfile
    required: false
    default: ./Dockerfile
  docker-context:
    description: Context used to build the Docker image
    required: false
    default: ./
  platforms:
    description: Comma-separated list of platforms the Docker image gets built for
    required: false
    default: linux/amd64
  docker-push-build-args:
    description: Build Args used when building the Docker image
    required: false
    default: ""
  docker-push-build-secrets:
    description: Secrets passed to docker-build-push action in yaml multiline format
    required: false
    default: ""
  docker-push-build-secret-files:
    description: Secret files passed to docker-build-push-action in yaml multiline format
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

      with:
        fetch-depth: 0
        ref: ${{ inputs.checkout-ref }}

    - shell: bash
      id: image-name
      run: |
        if [ -n "${{ inputs.image-name }}" ]
        then
          echo "::set-output name=value::$(echo ${{ inputs.image-name }})"
        else
          echo "::set-output name=value::$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
        fi

    - name: Install semantic-release
      shell: bash
      run: |
        sudo npm install -g \
          semantic-release@19 \
          @semantic-release/exec@6

        sudo wget -q https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Extract branch name
      shell: bash
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      id: extract_branch

    # This will set the version inside the container image
    # When no next version can be determined, the version will be set to the current version
    - name: set version of app
      shell: bash
      run: |

        if [ -n "${{ github.event.repository.default_branch }}" ]; then
          BRANCH_ADD=,"${{ github.event.repository.default_branch }}"
        else 
          BRANCH_ADD=
        fi        

        if [ -f package.json ]; then
          npm version $(git describe --tags --abbrev=0) --git-tag-version=false
          COMMAND="npm version \${nextRelease.version} --git-tag-version=false"
        elif [ -f pubspec.yaml ]; then
          yq -i e ".version = \"$(git describe --tags --abbrev=0)\"" pubspec.yaml
          COMMAND="yq -i e '.version = \\\"\${nextRelease.version}\\\"' pubspec.yaml"
        else
          COMMAND="echo Will release \${nextRelease.version}"
        fi


        # for scheduled runs we do not have the default_branch in the event
        if [ "${{ github.event.repository.default_branch }}"  == "" ] || [ "${{ github.event.repository.default_branch }}"  == "${GITHUB_REF#refs/*/}" ];then
          DEFAULT_BRANCH=
        else
          DEFAULT_BRANCH=,"${{ github.event.repository.default_branch }}"
        fi

        cat <<EOF > .releaserc.yaml
        branches: ["${GITHUB_REF#refs/*/}${DEFAULT_BRANCH}"]
        tagFormat: '\${version}'
        dryRun: true
        ci: true
        debug: true
        plugins:
          - '@semantic-release/commit-analyzer'
          - [
              '@semantic-release/exec',
              {
                'verifyReleaseCmd': "$COMMAND",
              },
            ]
        EOF

        npx semantic-release --debug

    # use specific commit-sha to be sure this is not changed
    - name: Maximize build space
      if: ${{ inputs.maximize-build-space == true }}
      uses: easimon/maximize-build-space@b4d02c14493a9653fe7af06cc89ca5298071c66e
      with:
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "true"
        build-mount-path: /var/lib/docker

    - name: Restart Docker service
      if: ${{ inputs.maximize-build-space == true }}
      shell: bash
      run: sudo service docker restart

    - id: docker_meta
      uses: docker/metadata-action@v3.5.0
      with:
        images: ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ steps.image-name.outputs.value }}
        tags: |
          type=schedule,pattern=nightly
          type=edge,branch=develop
          type=ref,event=pr
          type=ref,suffix=-{{sha}},event=branch

    - uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v1
      with:
        registry: ${{ inputs.image-registry }}
        username: ${{ inputs.image-registry-username }}
        password: ${{ inputs.image-registry-token }}

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        context: ${{ inputs.docker-context }}
        file: ${{ inputs.docker-file }}
        tags: |
          ${{ steps.docker_meta.outputs.tags }}
          ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ steps.image-name.outputs.value }}:${{ inputs.image-tag }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        cache-from: |
          ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ steps.image-name.outputs.value }}:main
          ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ steps.image-name.outputs.value }}:latest
          ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ steps.image-name.outputs.value }}:nightly
          ${{ steps.docker_meta.outputs.tags }}
          ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ steps.image-name.outputs.value }}:${{ inputs.image-tag }}
        cache-to: type=inline
        platforms: ${{ inputs.platforms }}
        load: true
        pull: true
        push: false
        build-args: ${{ inputs.docker-push-build-args }}
        secret-files: ${{ inputs.docker-push-build-secret-files }}
        secrets: ${{ inputs.docker-push-build-secrets }}

    - name: Test Docker image
      shell: bash {0}
      run: |
        docker run -d --name verify ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ steps.image-name.outputs.value }}:${{ inputs.image-tag }}
        counter=0
        until docker logs verify 2>&1 | ${{ inputs.container-verify-cmd }}
        do

          echo "Waiting for container to start up..."
          sleep 5

          docker ps -a 2>&1
          docker logs verify 2>&1

          if [ $counter -gt 20 ]
          then
            echo "Exiting after $counter retries!"
            exit 1
          fi

          ((counter++))
        done
        echo "Container started up successfully!"

    - name: Push Docker image
      shell: bash
      run: |
        tagsArr=(${{ steps.docker_meta.outputs.tags }} ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ steps.image-name.outputs.value }}:${{ inputs.image-tag }})

        for tag in ${tagsArr[@]}; do
          echo Pushing $tag;
          docker push $tag;
        done;
