name: "release-docker-image"
description: Tags a Docker Image with released version and signs it using Notary.
inputs:
  image-registry:
    description: Container registry where to push container images too
    required: false
    default: registry.neohelden.com
  image-registry-username:
    description: Username used to login at the image registry
    required: true
  image-registry-token:
    description: TOken use to login at the image registry
    required: true
  registry-org:
    description: Organization within the image registry where to push container images too
    required: false
    default: neohelden
  image-name:
    description: Name of the Docker image.
    required: false
    default: ${{ github.event.repository.name }}

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v1
      with:
        registry: ${{ inputs.image-registry }}
        username: ${{ inputs.image-registry-username }}
        password: ${{ inputs.image-registry-token }}

    - shell: bash
      run: |
        cat <<EOF > Dockerfile
        FROM ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ inputs.image-name }}:${{ github.sha }}
        EOF

    - uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ inputs.image-registry }}/${{ inputs.registry-org }}/${{ inputs.image-name }}:${{ github.event.release.tag_name }}
        push: true
