name: Build and Test
description: Builds and tests code using gradle

inputs:
  checkout-ref:
    description: Ref to checkout from Git
    default: ${{ github.event.pull_request.head.sha }}
    required: false

  pull-request-id:
    description: pull request id of the current build
    default: ${{ github.event.number }}
    required: false

  github-token:
    description: Token used for accessing GitHub.com
    required: true
  sonar-token:
    description: "Token used for pushing test results to SonarCloud.io"
    required: true
  sonar-project-base-dir:
    description: Use this property when you need the analysis to take place in a directory other than the one from which it was launched.
    default: ./
    required: false
  sonar-organization:
    description: The key of the organization to which the project belongs to
    default: neohelden
    required: false
  sonar-projectKey:
    description: The project's unique key. Allowed characters are letters, numbers, -, _, . and :, with at least one non-digit.
    default: ${{ github.event.repository.name }}
    required: false
  sonar-branch-name:
    description: Branch name to by analyzed.
    default: ${{ github.event.pull_request.head.ref}} || ${{ github.event.ref }}
    required: false
  sonar-xml-report-paths:
    description: Path to the XML Report file generated by jacocoTestReport
    default: build/reports/jacoco/test/jacocoTestReport.xml
    required: false

  sonar-exclusions:
    description: Paths excluded from Sonar analysis
    required: false
  sonar-coverage-exclusions:
    description: Paths excluded from Sonar coverage reporting.
    required: false

  default-branch:
    description: Default development branch of this repository
    default: ${{ github.event.repository.default_branch }}
    required: false

  target-branch:
    description: Target branch of a pull request
    default: ${{ github.base_ref }}
    required: false

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 ## fix shallow clone detected by SonarCloud.io
        ref: ${{ inputs.checkout-ref }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "adopt"

    - name: Check codeform
      uses: gradle/gradle-build-action@v2
      with:
        arguments: spotlessCheck --info

    - name: Compile
      uses: gradle/gradle-build-action@v2
      with:
        arguments: compileJava --info

    - name: Test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check jacocoTestReport --info

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: Test Results
        report_individual_runs: "true"
        files: |
          **/build/test-results/**/*.xml
          **/build/integTest-results/*.xml

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Prepare SonarCloud
      run: |
        curl --include \
          --request POST \
          --header "Content-Type: application/x-www-form-urlencoded" \
          -u ${{ inputs.sonar-token }} \
          -d 'project=neohelden-${{ inputs.sonar-projectKey }}&organization=${{ inputs.sonar-organization }}&name=${{ inputs.sonar-projectKey }}' \
          'https://sonarcloud.io/api/projects/create'

        curl --include \
          --request POST \
          --header "Content-Type: application/x-www-form-urlencoded" \
          -u ${{ inputs.sonar-token }} \
          -d 'project=neohelden-${{ inputs.sonar-projectKey }}&name=${{ inputs.default-branch }}' \
          'https://sonarcloud.io/api/project_branches/rename'
      shell: bash

    - name: SonarCloud Scan (PR Build)
      if: github.event_name == 'pull_request'
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          sonarqube 
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${{ inputs.sonar-organization }}
          -Dsonar.qualitygate.wait=true
          -Dsonar.scm.provider=git
          -Dsonar.projectKey=neohelden-${{ inputs.sonar-projectKey }}
          -Dsonar.login=${{ inputs.sonar-token }}
          -Dsonar.exclusions=${{ inputs.sonar-exclusions }}
          -Dsonar.pullrequest.key=${{ inputs.pull-request-id }}
          -Dsonar.pullrequest.base=${{ inputs.target-branch }}
          -Dsonar.pullrequest.branch=${{ inputs.sonar-branch-name }}
          -Dsonar.pullrequest.provider=github
          -Dsonar.pullrequest.github.repository=${{ github.event.repository.full_name}}
          -Dsonar.pullrequest.github.endpoint=https://api.github.com/
          --info
          --stacktrace
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}

    - name: SonarCloud Scan (Branch)
      if: github.event_name != 'pull_request'
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          sonarqube 
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${{ inputs.sonar-organization }}
          -Dsonar.coverage.jacoco.xmlReportPaths=${{ inputs.sonar-xml-report-paths }}
          -Dsonar.qualitygate.wait=true
          -Dsonar.scm.provider=git
          -Dsonar.projectKey=neohelden-${{ inputs.sonar-projectKey }}
          -Dsonar.login=${{ inputs.sonar-token }}
          -Dsonar.exclusions=${{ inputs.sonar-exclusions }}
          -Dsonar.branch.name=${{ inputs.sonar-branch-name }}
          --info
          --stacktrace
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
